import prisma from '@/lib/prisma'
import { generateInsights } from './insights'
import { generateWorkflowTasks } from './workflow'
import { detectAnomalies } from './anomaly'
import { generateBusinessAnalytics } from './analyst'
import type { ProactiveAlert } from './types'

export type { ProactiveAlert } from './types'

export async function generateProactiveAlerts(): Promise<ProactiveAlert[]> {
  const now = new Date().toISOString()
  const alerts: ProactiveAlert[] = []

  const [insights, tasks, anomalies, analytics] = await Promise.all([
    generateInsights(),
    generateWorkflowTasks(),
    detectAnomalies(),
    generateBusinessAnalytics(),
  ])

  for (const a of anomalies.filter(x => x.severity === 'high').slice(0, 4)) {
    alerts.push({
      id: `anomaly-${a.id}`,
      type: 'anomaly',
      priority: 'critical',
      title: a.title,
      message: a.description,
      href: a.href,
      createdAt: now,
    })
  }

  for (const t of tasks.filter(x => x.priority === 1).slice(0, 4)) {
    alerts.push({
      id: t.id,
      type: 'workflow',
      priority: 'high',
      title: t.title,
      message: t.description,
      href: t.href,
      createdAt: now,
    })
  }

  for (const i of insights.filter(x => x.type === 'critical' || x.type === 'warning').slice(0, 3)) {
    alerts.push({
      id: `insight-${i.id}`,
      type: 'insight',
      priority: i.type === 'critical' ? 'critical' : 'high',
      title: i.title,
      message: i.message,
      href: i.href,
      createdAt: now,
    })
  }

  const declining = analytics.comparisons.filter(c => c.trend === 'down' && c.changePct < -10)
  for (const c of declining.slice(0, 2)) {
    alerts.push({
      id: `analytics-${c.label}`,
      type: 'analytics',
      priority: 'medium',
      title: `Penurunan: ${c.label}`,
      message: `Turun ${Math.abs(c.changePct)}% (${c.current} vs ${c.previous}).`,
      href: '/',
      createdAt: now,
    })
  }

  const priorityOrder = { critical: 0, high: 1, medium: 2 }
  alerts.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority])
  return alerts.slice(0, 12)
}

export async function exportDailySummaryMarkdown(): Promise<string> {
  const [insights, tasks, anomalies, analytics, predictions] = await Promise.all([
    generateInsights(),
    generateWorkflowTasks(),
    detectAnomalies(),
    generateBusinessAnalytics(),
    import('./predictions').then(m => m.generatePredictions()),
  ])

  const date = new Date().toLocaleDateString('id-ID', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })

  let md = `# SJ Kitchen AI Daily Summary\n**${date}**\n\n`
  md += `## Ringkasan Eksekutif\n${analytics.summary}\n\n`

  md += `## Prioritas Hari Ini\n`
  for (const t of tasks.filter(x => x.priority <= 2).slice(0, 8)) {
    md += `- **[P${t.priority}]** ${t.title}: ${t.description}\n`
  }
  md += `\n`

  md += `## AI Insights\n`
  for (const i of insights) {
    md += `- **${i.title}** (${i.type}): ${i.message}\n`
    if (i.action) md += `  - Aksi: ${i.action}\n`
  }
  md += `\n`

  md += `## Anomali Terdeteksi\n`
  if (anomalies.length === 0) {
    md += `Tidak ada anomali.\n\n`
  } else {
    for (const a of anomalies) {
      md += `- **[${a.severity.toUpperCase()}]** ${a.title}: ${a.description}\n`
    }
    md += `\n`
  }

  md += `## Prediksi\n`
  for (const p of predictions) {
    md += `- **${p.title}**: ${p.value} (confidence: ${p.confidence} ${p.confidencePct}%)\n`
    md += `  - ${p.reasoning}\n`
  }
  md += `\n---\n*Generated by SJ Kitchen AI Copilot*\n`

  return md
}

export async function exportConversationMarkdown(conversationId: string, userId: string): Promise<string | null> {
  const conversation = await prisma.conversation.findFirst({
    where: { id: conversationId, userId },
    include: { messages: { orderBy: { createdAt: 'asc' } } },
  })

  if (!conversation) return null

  const title = conversation.title || 'Percakapan AI'
  let md = `# ${title}\n`
  md += `*Exported ${new Date().toLocaleString('id-ID')}*\n\n`

  for (const msg of conversation.messages) {
    const role = msg.role === 'user' ? 'Anda' : 'AI Copilot'
    md += `### ${role}\n${msg.content}\n\n`
  }

  md += `---\n*SJ Kitchen AI Copilot Export*\n`
  return md
}
